### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by chopfitzroy** [stephenway/postcss.vim#1]
Based off the README I notice the project is a still a WIP, but based of the last commit (9 months) have you discontinued development of this plugin?

**Comment by stephenway** [comment]
Yea sorry, I've since switched to using spacemacs and I don't really need this anymore, but your welcome to fork or start your own if you'd like?

**Comment by chopfitzroy** [comment]
Hey @stephenway,

Will definitely think about it :).

Cheers.
